version: '2'
services:
  maxapi:
    build: .
    command: bash -c 'rails s -b 0.0.0.0 -p 9292'
    environment:
      - MAXSCALE_MAXINFO_IP_PORT=10.190.0.116:8003
    ports:
      - "9292:9292"
    volumes:
      - $PWD:/opt/maxapi
    volumes_from:
      - container:mrmcompose_maxscale_1:ro
